"""Generate per-item DOCX files for supporting evidence.

Each appendix item (CV, syllabus, etc.) the wizard's user accepts becomes
a single DOCX uploaded to S3. The format is intentionally simple — title
+ provenance + body paragraphs — so downstream readers see a clean,
standalone document.

Layout:
    Title:    {item heading}
    Subtitle: Supporting Evidence for Standard {std}.{spec}
    Body:     {item body paragraphs}
    Footer:   Generated by CSHSE AI Import Wizard on {date} from
              "{original_filename}" v{N}

S3 key pattern (mirrors existing SupportingEvidence convention):
    {institutionId}/{versionId}/{slug}.docx
"""
from __future__ import annotations

import io
import re
import uuid
from dataclasses import dataclass
from datetime import datetime

from docx import Document
from docx.shared import Pt


@dataclass
class ExportedItem:
    """Describes a single exported supporting-evidence DOCX."""
    item_id: str
    standard_code: str
    spec_code: str
    title: str
    docx_bytes: bytes
    suggested_filename: str
    sha256: str


def _slugify(s: str, max_len: int = 60) -> str:
    """Filesystem-safe filename slug."""
    s = re.sub(r"[^A-Za-z0-9._\-\s]", "", s)
    s = re.sub(r"\s+", "_", s).strip("_")
    return s[:max_len] or "item"


def build_evidence_docx(
    title: str,
    body_text: str,
    standard_code: str,
    spec_code: str,
    source_filename: str = "(unknown source)",
    source_version: int | None = None,
) -> ExportedItem:
    """Create a DOCX for one supporting-evidence item.

    ``body_text`` may contain multiple paragraphs separated by ``\\n\\n``.
    """
    import hashlib

    doc = Document()

    # Title
    heading = doc.add_heading(title or "(untitled)", level=1)

    # Subtitle: which spec this evidence supports
    sub = doc.add_paragraph()
    sub_run = sub.add_run(f"Supporting Evidence for Standard {standard_code}.{spec_code}")
    sub_run.italic = True
    sub_run.font.size = Pt(11)

    # Body paragraphs
    for para in (body_text or "").split("\n\n"):
        para = para.strip()
        if para:
            doc.add_paragraph(para)

    # Footer/provenance
    doc.add_paragraph()
    foot = doc.add_paragraph()
    foot_run = foot.add_run(
        f"— Generated by the CSHSE AI Import Wizard on "
        f"{datetime.utcnow().strftime('%Y-%m-%d')} from “{source_filename}”"
        + (f" v{source_version}" if source_version else "")
    )
    foot_run.italic = True
    foot_run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    bytes_ = buf.getvalue()
    sha = hashlib.sha256(bytes_).hexdigest()

    item_id = uuid.uuid4().hex
    slug = _slugify(title)
    filename = f"{standard_code}-{spec_code}-{slug}.docx"

    return ExportedItem(
        item_id=item_id,
        standard_code=standard_code,
        spec_code=spec_code,
        title=title,
        docx_bytes=bytes_,
        suggested_filename=filename,
        sha256=sha,
    )
