"""Upload generated supporting-evidence DOCX files to S3 + create the
matching ``SupportingEvidence`` rows in MongoDB.

S3 key convention (matches existing CSHSE evidence storage):
    {institutionId}/{versionId}/{filename}

MongoDB row matches the existing ``SupportingEvidence`` schema fields.
"""
from __future__ import annotations

import os
import uuid
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

import boto3

from app.export.docx_writer import ExportedItem


@dataclass
class UploadedEvidence:
    s3_key: str
    s3_bucket: str
    docx_size: int
    sha256: str
    supporting_evidence_doc: dict  # the dict that becomes the Mongo row


def _s3_client():
    return boto3.client(
        "s3",
        endpoint_url=os.environ.get("AWS_ENDPOINT_URL"),
        aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
        region_name=os.environ.get("AWS_DEFAULT_REGION") or "auto",
    )


def upload_evidence_docx(
    item: ExportedItem,
    institution_id: str,
    submission_id: str,
    uploaded_by: str,
    bucket: Optional[str] = None,
    *,
    dry_run: bool = False,
) -> UploadedEvidence:
    """Upload one generated DOCX to S3 + return the SupportingEvidence row spec.

    The caller is responsible for inserting the returned ``supporting_evidence_doc``
    into the ``supportingevidences`` Mongo collection — we don't take a Mongo
    connection here to keep this module dependency-light.
    """
    bucket = bucket or os.environ["AWS_S3_BUCKET_NAME"]
    version_id = uuid.uuid4().hex[:24]  # match Mongo's 24-char ObjectId look-and-feel
    s3_key = f"{institution_id}/{version_id}/{item.suggested_filename}"

    if not dry_run:
        client = _s3_client()
        client.put_object(
            Bucket=bucket,
            Key=s3_key,
            Body=item.docx_bytes,
            ContentType=(
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            ),
        )

    se_doc = {
        "institutionId": institution_id,
        "submissionId": submission_id,
        "uploadedBy": uploaded_by,
        "standardCode": item.standard_code,
        "specCode": item.spec_code,
        "evidenceType": "document",
        "file": {
            "filename": item.suggested_filename,
            "originalName": f"{item.title}.docx",
            "mimeType": (
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            ),
            "size": len(item.docx_bytes),
            "s3Key": s3_key,
            "s3Bucket": bucket,
            "storageType": "s3",
        },
        "versionId": version_id,
        "versionNumber": 1,
        "isCurrentVersion": True,
        "description": (
            f"Auto-split supporting evidence for Standard {item.standard_code}."
            f"{item.spec_code} — generated by AI Import Wizard"
        ),
        "tags": ["ai-import-wizard", f"std-{item.standard_code}"],
        "isDeleted": False,
        "createdAt": datetime.utcnow(),
        "updatedAt": datetime.utcnow(),
    }
    return UploadedEvidence(
        s3_key=s3_key,
        s3_bucket=bucket,
        docx_size=len(item.docx_bytes),
        sha256=item.sha256,
        supporting_evidence_doc=se_doc,
    )
