/**
 * Level-aware CSHSE standards catalog (associate / baccalaureate / masters).
 *
 * The official CSHSE National Standards differ by degree level — Standard 4 is
 * "Program Evaluation" for an associate program but the numbering, titles and
 * specification criteria are level-specific. Each institution declares its level
 * (`Submission.programLevel`), and the AI evaluation rubric MUST use that level's
 * criteria.
 *
 * Data source: `standardsByLevel.json`, generated by
 * `scripts/generate_standards_catalog.py` from the official CSHSE National
 * Standards PDFs (July 2025). Baccalaureate is taken verbatim from the verified
 * `baccalaureate_2025` dataset; associate + masters are parsed from their PDFs.
 * The `criteria` text embeds the "Provide the following: 1… 2…" reader-report
 * checklist items, so the rubric reflects both the Standard and the reader-report
 * specification detail derived from it.
 *
 * The legacy flat `standards.ts` catalog remains as a last-resort fallback so no
 * caller ever gets an empty rubric.
 */
import catalog from './standardsByLevel.json';
import { getStandardByCode } from './standards';

export type ProgramLevel = 'associate' | 'baccalaureate' | 'masters';

interface SpecEntry {
  title: string;
  criteria: string;
}
interface StandardEntry {
  title: string;
  specs: Record<string, SpecEntry>;
}
type LevelCatalog = Record<string, StandardEntry>;
const CATALOG = catalog as unknown as Record<string, LevelCatalog>;

/** Normalize any stored/legacy level value to the three canonical catalog keys. */
export function normalizeLevel(programLevel?: string | null): ProgramLevel {
  const pl = String(programLevel || '').trim().toLowerCase();
  if (pl === 'associate' || pl === 'aa' || pl === 'associates') return 'associate';
  if (pl.startsWith('master')) return 'masters';
  // bachelors / bachelor / baccalaureate / default
  return 'baccalaureate';
}

export interface SpecCriteria {
  standardCode: string;
  specCode: string;
  standardTitle: string;
  /** The rubric text handed to the AI evaluator (standard + reader-report detail). */
  criteria: string;
  /** Which catalog satisfied the lookup — for logging/diagnostics. */
  source: 'level' | 'legacy';
}

/**
 * Resolve the rubric criteria for a (level, standard, spec). Falls back to the
 * legacy flat catalog only when the level catalog has no entry, so validation is
 * never left without a rubric.
 */
export function getSpecCriteria(
  programLevel: string | null | undefined,
  standardCode: string,
  specCode: string
): SpecCriteria | null {
  const level = normalizeLevel(programLevel);
  const std = CATALOG[level]?.[String(standardCode)];
  const spec = std?.specs?.[String(specCode)];
  if (std && spec && spec.criteria) {
    return {
      standardCode: String(standardCode),
      specCode: String(specCode),
      standardTitle: std.title || spec.title || '',
      criteria: spec.criteria,
      source: 'level',
    };
  }
  // Fallback: legacy flat standards.ts
  const legacyStd = getStandardByCode(String(standardCode));
  const legacySpec = legacyStd?.specifications?.find((s) => s.code === String(specCode));
  if (legacyStd && legacySpec) {
    return {
      standardCode: String(standardCode),
      specCode: String(specCode),
      standardTitle: legacyStd.title || '',
      criteria: legacySpec.text || '',
      source: 'legacy',
    };
  }
  return null;
}

/**
 * The full standards list for a level, shaped like `getAllStandards()` (code +
 * title + specifications[{code,title,text}]) so the /api/standards route and the
 * client catalog can render level-correct titles. Falls back to the legacy flat
 * catalog when a level is somehow absent.
 */
export function getLevelStandards(programLevel: string | null | undefined) {
  const level = normalizeLevel(programLevel);
  const lvl = CATALOG[level];
  if (!lvl) return null;
  return Object.keys(lvl)
    .sort((a, b) => Number(a) - Number(b))
    .map((code) => {
      const std = lvl[code];
      const specs = Object.keys(std.specs).sort();
      return {
        code,
        title: std.title,
        specifications: specs.map((sc) => ({
          code: sc,
          title: std.title,
          text: std.specs[sc].criteria,
        })),
      };
    });
}

export function hasLevelCatalog(programLevel: string | null | undefined): boolean {
  return !!CATALOG[normalizeLevel(programLevel)];
}
